# Generated by Django 3.0.2 on 2020-01-18 18:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ('username',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(blank=True, max_length=512, null=True)),
                ('question_answer', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(upload_to='images')),
                ('post_text', models.CharField(blank=True, max_length=512, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=512, null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meanit_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_msg', models.CharField(max_length=512, unique=True)),
                ('msg_text', models.CharField(max_length=512)),
                ('msg_read', models.BooleanField(blank=True, null=True)),
                ('msg_date', models.DateField()),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meanit_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('hashtag', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meanit_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.CharField(blank=True, max_length=512, null=True)),
                ('post_text', models.CharField(blank=True, max_length=512, null=True)),
                ('cmnt_read', models.BooleanField(blank=True, null=True)),
                ('cmnt_date', models.BooleanField(blank=True, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meanit_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MeanitUserQuestions',
            fields=[
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meanit_app.Profile')),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='meanit_app.Questions')),
            ],
        ),
    ]
