# Generated by Django 3.0.2 on 2020-01-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meanit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='profile_user',
            new_name='profile_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='original_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meanit_app.Post'),
        ),
    ]
