# Generated by Django 3.0.2 on 2020-01-18 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meanit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meanituserquestions',
            name='question',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='meanit_app.Questions'),
        ),
    ]
