# Generated by Django 3.0.2 on 2020-01-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meanit_app', '0002_meanituserquestions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meanituserquestions',
            name='question',
        ),
    ]
