# Generated by Django 3.0.2 on 2020-01-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meanit_app', '0002_auto_20200117_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meanituserquestions',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='meanituserquestions',
            name='question_name',
        ),
        migrations.AddField(
            model_name='meanituserquestions',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='meanit_app.Questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_answer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
