# Generated by Django 3.0.2 on 2020-01-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meanit_app', '0003_auto_20200119_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_answer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
